const fs = require("fs");

const raw = String(process.env.RAILWAY_API_URL || "").trim().replace(/\/+$/, "");

if (!raw) {
  console.error("ERROR: RAILWAY_API_URL belum diatur di Netlify Environment Variables.");
  process.exit(1);
}

let backend;
try {
  backend = new URL(raw);
} catch {
  console.error("ERROR: RAILWAY_API_URL bukan URL yang valid.");
  process.exit(1);
}

if (!["https:", "http:"].includes(backend.protocol)) {
  console.error("ERROR: RAILWAY_API_URL harus menggunakan http:// atau https://");
  process.exit(1);
}

const apiBase = `${raw}/api`;

const output = `// Auto-generated by Netlify build. Do not edit manually.
window.APP_CONFIG = {
  API_BASE_URL: ${JSON.stringify(apiBase)}
};
`;

fs.writeFileSync("config.js", output, "utf8");
console.log(`Frontend API configured: ${apiBase}`);
